### ISSUE TITLE
Title parser fault

### ISSUE THREAD

**Issue by ghost** [alexhor/include_sermon#1]
The post title is not generated correctly.
Post was generated with following link: https://www.dropbox.com/s/xnf8860s0ngboga/2015-11-08%20Und%20du...-%20Pfr.%20Armin%20Graf.mp3?dl=0

The resulting title was "Und du...- Pfr. Armin Graf.mp3?dl=0 // Und du...- Pfr. Armin Graf"

**Comment by alexhor** [comment]
The problem was that there wasn't a space before the last "-" and that was required.
However I fixed the issue and now the programm doesn't care if there are spaces or not.
